<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <UseWPF>true</UseWPF>
    <RootNamespace>Clock.Windows</RootNamespace>
    <AssemblyName>Clock.Windows</AssemblyName>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <ApplicationManifest>app.manifest</ApplicationManifest>
    <ApplicationIcon>Assets\icon.ico</ApplicationIcon>
  </PropertyGroup>

  <ItemGroup>
    <Resource Include="Assets\icon.ico" />
  </ItemGroup>

  <ItemGroup>
    <None Include="Data\cities.json" CopyToOutputDirectory="PreserveNewest" />
    <None Include="Data\cities.zh-CN.json" CopyToOutputDirectory="PreserveNewest" />
  </ItemGroup>

</Project>
